dist: xenial
language: go
go:
 - "1.12.3"

env:
  global:
    - GO111MODULE=on
  matrix:
    - CGO_LDFLAGS="-lopenblas"
    - CGO_LDFLAGS="-lopenblas" CGO_CFLAGS="-std=gnu99 -DBLAS"
    - MKLVER="2019.3.199" LD_LIBRARY_PATH="/opt/intel/compilers_and_libraries_$MKLVER/linux/mkl/lib/intel64" CGO_LDFLAGS="-L $LD_LIBRARY_PATH -lmkl_rt"
    - MKLVER="2019.3.199" LD_LIBRARY_PATH="/opt/intel/compilers_and_libraries_$MKLVER/linux/mkl/lib/intel64" CGO_LDFLAGS="-L $LD_LIBRARY_PATH -lmkl_rt" CGO_CFLAGS="-std=gnu99 -DBLAS -DMKL"

before_install:
 - if [ -n "$MKLVER" ]; then wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'; fi
 - sudo apt update
 - if [ -n "$MKLVER" ]; then sudo apt install intel-mkl-core-rt-$MKLVER -y;  fi
 - if [ -z "$MKLVER" ]; then sudo apt install libopenblas-dev -y; fi
